/**
 * Global catalogue of professional / technical skills used by job forms and
 * candidate filters. Grouped by category for maintainability and exposed as a
 * flat, de-duplicated list (`SKILLS`) plus grouped options for pickers.
 */
export const SKILL_GROUPS: Record<string, string[]> = {
  Languages: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "Kotlin",
    "Swift",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Scala",
    "Elixir",
    "Dart",
    "R",
    "MATLAB",
    "Objective-C",
    "Perl",
    "Haskell",
    "Clojure",
    "Solidity",
    "SQL",
    "Bash",
  ],
  Frontend: [
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt",
    "Angular",
    "Svelte",
    "SvelteKit",
    "Remix",
    "Astro",
    "Redux",
    "Zustand",
    "Tailwind CSS",
    "CSS",
    "HTML",
    "Sass",
    "Material UI",
    "shadcn/ui",
    "Framer Motion",
    "Three.js",
    "Webpack",
    "Vite",
  ],
  Backend: [
    "Node.js",
    "Express",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Ruby on Rails",
    "Laravel",
    ".NET",
    "ASP.NET",
    "GraphQL",
    "REST APIs",
    "gRPC",
    "tRPC",
    "Prisma",
    "Microservices",
  ],
  Mobile: [
    "React Native",
    "Flutter",
    "iOS",
    "Android",
    "SwiftUI",
    "Jetpack Compose",
    "Expo",
  ],
  Databases: [
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Elasticsearch",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Supabase",
    "Neo4j",
    "Snowflake",
    "BigQuery",
  ],
  "DevOps & Cloud": [
    "AWS",
    "Google Cloud",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "CI/CD",
    "GitHub Actions",
    "Jenkins",
    "Nginx",
    "Linux",
    "Serverless",
    "Cloudflare",
    "Vercel",
  ],
  "Data & AI": [
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "scikit-learn",
    "Data Analysis",
    "Data Engineering",
    "NLP",
    "Computer Vision",
    "LLMs",
    "LangChain",
    "Apache Spark",
    "Airflow",
    "Power BI",
    "Tableau",
  ],
  "Design & Product": [
    "Figma",
    "UI Design",
    "UX Design",
    "UX Research",
    "Product Design",
    "Design Systems",
    "Prototyping",
    "Wireframing",
    "Accessibility",
    "Adobe XD",
    "Sketch",
  ],
  "Practices & Tools": [
    "Git",
    "Agile",
    "Scrum",
    "Jira",
    "Testing",
    "Jest",
    "Cypress",
    "Playwright",
    "TDD",
    "System Design",
    "Code Review",
    "Technical Writing",
    "Project Management",
  ],
};

/** Flat, de-duplicated, alphabetically sorted list of every skill. */
export const SKILLS: string[] = Array.from(
  new Set(Object.values(SKILL_GROUPS).flat())
).sort((a, b) => a.localeCompare(b));

/** Option shape ready for the MultiSelect component. */
export const SKILL_OPTIONS = SKILLS.map((skill) => ({
  value: skill,
  label: skill,
}));
